version: "3.7"
services:
  tiny_service:
    container_name: tiny_service
    build: ./app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - tiny_db

  tiny_db:
    container_name: tiny_db
    image: "mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: tiny
      MYSQL_ROOT_PASSWORD: root
