server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tiny?useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    root: ERROR
    run.tinyurl: DEBUG
    org.hibernate: DEBUG
